### ISSUE TITLE
Create a UI for whitebox server using `streamlit` or similar tools

### ISSUE THREAD

**Issue by momegas** [whitebox-ai/whitebox#114]
**Is your feature request related to a problem? Please describe.**
There is no easy way for someone to visualize info / metrics in whitebox

**Describe the solution you'd like**
Use a fast prototyping tool like `streamlit` to create a working UI, so that the user can visualise metrics, inferences, monitors, and alerts.

**Describe alternatives you've considered**
Issues #113 and #85 

**Additional context**
You can find examples in the mock UI: https://www.figma.com/file/dqKkrdj81XRF0WDum5HTma/Whitebox-Design-(MatteUI-Kit)---Inter?node-id=801%3A1857

**Comment by momegas** [comment]
@stavrostheocharis what do you think about this?
You have the most experience with streamlit. Think we can make it happen?
I can provide assistance with the SDK and we could use it in the streamlit app.

**Comment by stavrostheocharis** [comment]
I will have a deep look on figma templates for most features I see them, we can have something. For some more "complex" features maybe find a workaround

**Comment by momegas** [comment]
No need to copy everything. Just give someone the ability to view the data.
OK so I can assign this to you then and you can have a look?

**Comment by stavrostheocharis** [comment]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/55717550/221165030-b4bf05ef-57bc-4fc2-b500-e57808b8642b.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/55717550/221165116-51b669c4-acd5-4523-9393-7552fa3d765d.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/55717550/221165179-a8161909-046c-4707-88ce-efdbb8805d39.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/55717550/221167838-3c3e9b6e-47a6-4026-82b1-6e02321c287f.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/55717550/221165282-5c7d324b-f3c2-43fa-8c09-9925bbec77fb.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/55717550/221165409-8b88438f-e087-421c-9b62-bce34b457b47.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/55717550/221165475-60ff71b2-9c93-404d-8787-f3682d7e4578.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/55717550/221165514-b875fe6b-0c3f-47d9-9b36-d55733795fbb.png">
