### ISSUE TITLE
Inference timestamp is saved as created_at in database

### ISSUE THREAD

**Issue by stavrostheocharis** [whitebox-ai/whitebox#137]
**Describe the bug**
Inference timestamp is saved as created_at in database. Should be the actual timestamp of client's data.

**To Reproduce**
Just create any report based on report functions (performance metrics, drift etc.)

**Expected behaviour**
Timestamp should be the data's actual timestamp. This ticket is highly related to #126 . Actually is blocked by this.

**Comment by stavrostheocharis** [comment]
@NickNtamp please elaborate based on the above template

**Comment by momegas** [comment]
We should be using the timestamp of the inference instead of `now()` method
