### ISSUE TITLE
 There should be raised an error in case the target column is not included inside the processed data of the given inference

### ISSUE THREAD

**Issue by stavrostheocharis** [whitebox-ai/whitebox#138]
**Description**

The user provides his model data and also separately his inference data. There should be raised an error in case the target column is not included inside the processed data of the given inference.

**Solution**

Create a function that checks if the target column is being included inside the processed data of the given inference.

**Additional context**
![Nikos Ntampakis, 2 weeks ago  4 authors (John Zaras and others)](https://user-images.githubusercontent.com/55717550/219068225-d7c405ee-ce49-4b0b-a43a-159823117f76.png)
![John Zaras, 3 months ago 1 author (John Zaras)](https://user-images.githubusercontent.com/55717550/219068258-af19eeff-e635-42d8-b609-6651ca8cd7d8.png)

**Comment by stavrostheocharis** [comment]
It is solved in https://github.com/whitebox-ai/whitebox/pull/131/commits/0648112dabc018a2574ecc405a1be5fe39d30fd5 commit in https://github.com/whitebox-ai/whitebox/pull/131

**Comment by momegas** [comment]
Closing this then 🙏
