### ISSUE TITLE
SDK example notebook has wrong outputs and not all functions

### ISSUE THREAD

**Issue by stavrostheocharis** [whitebox-ai/whitebox#139]
**Describe the bug**
The outputs of the SDK example notebook are wrong (maybe they are based in old schemas)

**To Reproduce**
1. You can just open the notebook and check the outputs of the cells

**Expected behavior**
We do not need the "features" and the "probability" here. Maybe if you rerun the cells of the notebook it will produce the right results, because now the schemas have been changed.

**Screenshots**
!['updated_at' '2023-01-17T150227 356199',](https://user-images.githubusercontent.com/55717550/219068849-1766e8cb-5771-4b3e-bce1-d1258bcaf72d.png)

**Additional context**
Also change the title to : 
"Use of Whitebox SDK" or "Use of Whitebox SDK" or "How to use the Whitebox SDK"
![Usaging Whitebox SDK](https://user-images.githubusercontent.com/55717550/219069598-3bd09f88-c333-44a6-b766-6e1b7f99503d.png)

- [x] Fix the outputs of the notebook
- [x] Correct the title
- [x] Also include the new functions in the notebook

**Comment by NickNtamp** [comment]
We will create another notebook with visualizations for the rest of the functions (when ready). I am done with the rest of open points of this ticket.
