### ISSUE TITLE
Change the name of the prediction column

### ISSUE THREAD

**Issue by stavrostheocharis** [whitebox-ai/whitebox#140]
**Description**

In model base name the target column of the prediction as "prediction"
Need to change it because it creates confusion.

**Solution**

Change the name of the "prediction" to "target_column".
Make the appropriate changes across the code where this variable sis being used.

**Additional context**

<img width="401" alt="Nikos Ntampakis, 2 weeks ago  4 authors (John Zaras and others)" src="https://user-images.githubusercontent.com/55717550/219070751-4b63ad28-d227-41ee-aa89-9de97cb1dd92.png">

**Comment by stavrostheocharis** [comment]
It is solved in a commit in https://github.com/whitebox-ai/whitebox/issues/114#event-8387922964

**Comment by momegas** [comment]
Closing this 🙏
