### ISSUE TITLE
Create PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by renatocmaciel** [whitebox-ai/whitebox#152]
**Is your feature request related to a problem? Please describe.**
Improve repository code standards by creating a pull request template.

**Describe the solution you'd like**
Create a simple PR template to enforce repo standards on prs.
Might use [pandas pr template](https://github.com/pandas-dev/pandas/blob/main/.github/PULL_REQUEST_TEMPLATE.md) as reference.

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

**Comment by momegas** [comment]
Feel free to open a pull request 👍 
Some notes: 
- the links link to pandas
- also this `doc/source/whatsnew/vX.X.X.rst` is not relevant to us. Maybe replace it with adding the docs needed in the right docs path
